vich_uploader:
    db_driver: orm
    storage: file_system
    mappings:
        your_mapping_name:
            uri_prefix: /uploads/offres
            upload_destination: '%kernel.project_dir%/public/uploads/offres'