vich_uploader:
    db_driver: orm
    mappings:
        offre_images:
            uri_prefix: /uploads/offres
            upload_destination: '%kernel.project_dir%/public/uploads/offres'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false